FROM jmfirth/webpack:8

# @see http://label-schema.org/rc1/
#LABEL maintainer="Phase2 <outrigger@phase2technology.com>" \
#  org.label-schema.vendor="Phase2 <outrigger@phase2technology.com>" \
#  org.label-schema.name="Outrigger pa11y dashboard" \
#  org.label-schema.description="Docker image for displaying pa11y-ci results generated by outrigger/pa11y." \

# add git so we can add our dashboard
RUN apt-get install -y git

# clone the dashboard repo, install deps
RUN cd / && git clone -b remove-pa11y-deps --single-branch https://github.com/tjheffner/vue-pa11y.git app && cd app && npm install
